### ISSUE TITLE
Sound in videos not playing

### ISSUE THREAD

**Issue by ghost** [flathub/org.gnome.gitlab.YaLTeR.Identity#2]
The sound is not playing with my video files, other players work.
The first video I tried is a WebM-Video (video/webm) with the VP9 Video-Codec and the Opus Audio-Codec.
The second video I tried is a Matroska-Video (video/x-matroska) with the H.265 (Main 10 Profile) Video-Codec and the MPEG-4 AAC Audio-Codec.

Fedora Linux 36.20220815.0 (Silverblue)
Identity Version (Flatpak): 0.3.0

**Comment by YaLTeR** [comment]
Identity disables sound in videos intentionally since it's a visual comparison program. While you could make an argument that you could switch the sound to the currently open tab too right now to compare the sound, this is not the intended use-case, and it will break when I add new comparison modes in the future which will show multiple videos at once side by side.
